---
apiVersion: v1
kind: Pod
metadata:
  labels:
    role: backend
  name: backend
spec:
  containers:
  - image: nginx
    name: backend
    ports:
    - containerPort: 80
    resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: backend
  name: backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    role: backend
