---
apiVersion: v1
kind: Pod
metadata:
  labels:
    role: frontend
  name: frontend
spec:
  containers:
  - image: nginx
    name: frontend
    ports:
    - containerPort: 80
    resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: frontend
  name: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    role: frontend
